# Generated by Django 4.0.4 on 2022-07-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('category_image', models.ImageField(null=True, upload_to='categorias')),
                ('url_name', models.CharField(max_length=30)),
            ],
        ),
    ]
