# Generated by Django 4.0.4 on 2022-07-16 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subasta_app', '0002_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_ganador', models.IntegerField(blank=True, null=True)),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subasta_app.articulo')),
                ('user_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
