# Generated by Django 4.0.4 on 2022-07-24 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subasta_app', '0002_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_ganador', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_limite', models.DateField()),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subasta_app.articulo')),
                ('user_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subasta_app.articulo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subasta_app.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('genere', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('image', models.ImageField(blank=True, default='./user_images/anonimo.svg', null=True, upload_to='user_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
