# Generated by Django 4.0.4 on 2022-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta_app', '0003_subasta_puja_publicacion_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
