# Generated by Django 4.0.4 on 2022-07-30 03:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subasta_app', '0004_articulo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=80, populate_from='nombre', unique=True),
        ),
    ]
