# Generated by Django 4.0.4 on 2022-07-20 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subasta_app', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subasta_app.articulo')),
            ],
        ),
    ]
